server:
  port: 9999
spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/lattechain?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/templates/, classpath:/static/
